messages:
  barrel:
    obtain: "&bYou were given &a{amount} &bbarrel(s)!"
    denied: "&cYou do not have access to this barrel!"
  friend:
    add-pass: "&b{target} &7can now access this barrel!"
    add-fail: "&b{target} &7already has access this barrel!"
    del-pass: "&b{target} &7can no longer access this barrel!"
    del-fail: "&b{target} &7already can't access this barrel!"

menu:
  values:
    B: BLACK_STAINED_GLASS_PANE
    W: WHITE_STAINED_GLASS_PANE
    G:
      type: LIME_STAINED_GLASS_PANE
      name: "&aPut items in here!"
    Y:
      type: YELLOW_STAINED_GLASS_PANE
      name: "&eTake items from here!"
    I: item_input
    O: item_output
  layout:
    1: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ Y ║ O ║ Y ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    2: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ W ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    3: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    4: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ Y ║ Y ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    5: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ Y ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    6: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    7: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ Y ║ Y ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    8: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ Y ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
    9: |
      ╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ I ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ W ║ G ║ G ║ G ║ W ║ O ║ O ║ O ║ W ║
      ╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
      ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║ B ║
      ╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝